server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 80

swagger:
  resourcePackage: org.sample.elastic.services.resources

elasticsearch.host: localhost[9300-9400] 
elasticsearch.cluster: elasticsearch-local
elasticsearch.clientnode: javaclient
elasticsearch.clientport: 10080